/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dwichan.tempconverter;

import java.text.DecimalFormat;

/**
 *
 * @author Dwi Candra Permana
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrTo = new javax.swing.ButtonGroup();
        pnFrom = new javax.swing.JPanel();
        txtCelcius = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnTo = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        pnResult = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblResult = new javax.swing.JTextArea();
        cmbLang = new javax.swing.JComboBox<>();
        btnConv = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter by DwiChan0905");
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.UTILITY);

        pnFrom.setBorder(javax.swing.BorderFactory.createTitledBorder("From Celcius"));

        txtCelcius.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("°C");

        javax.swing.GroupLayout pnFromLayout = new javax.swing.GroupLayout(pnFrom);
        pnFrom.setLayout(pnFromLayout);
        pnFromLayout.setHorizontalGroup(
            pnFromLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFromLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnFromLayout.setVerticalGroup(
            pnFromLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFromLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFromLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Temperature Converter");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ver. 1.0");

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Created by Dwi Candra Permana (https://github.com/dwichan0905)");

        pnTo.setBorder(javax.swing.BorderFactory.createTitledBorder("To"));

        bgrTo.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Fahrenheit (°F)");
        jRadioButton1.setActionCommand("f");

        bgrTo.add(jRadioButton2);
        jRadioButton2.setText("Reamur (°R)");
        jRadioButton2.setActionCommand("r");

        bgrTo.add(jRadioButton3);
        jRadioButton3.setText("Kelvin (K)");
        jRadioButton3.setActionCommand("k");

        javax.swing.GroupLayout pnToLayout = new javax.swing.GroupLayout(pnTo);
        pnTo.setLayout(pnToLayout);
        pnToLayout.setHorizontalGroup(
            pnToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnToLayout.setVerticalGroup(
            pnToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnToLayout.createSequentialGroup()
                .addGroup(pnToLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        lblResult.setEditable(false);
        lblResult.setColumns(20);
        lblResult.setLineWrap(true);
        lblResult.setRows(5);
        lblResult.setWrapStyleWord(true);
        lblResult.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(lblResult);

        javax.swing.GroupLayout pnResultLayout = new javax.swing.GroupLayout(pnResult);
        pnResult.setLayout(pnResultLayout);
        pnResultLayout.setHorizontalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnResultLayout.setVerticalGroup(
            pnResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        cmbLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English (United States)", "Bahasa Indonesia", "Basa Sunda" }));
        cmbLang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLangItemStateChanged(evt);
            }
        });

        btnConv.setText("Convert");
        btnConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pnFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnConv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConv)
                    .addComponent(btnClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLangItemStateChanged
        // TODO add your handling code here:
        switch (cmbLang.getSelectedIndex()) {
            case 0:
                pnFrom.setBorder(javax.swing.BorderFactory.createTitledBorder("From Celcius"));
                pnTo.setBorder(javax.swing.BorderFactory.createTitledBorder("To"));
                pnResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
                btnConv.setText("Convert");
                btnClose.setText("Close");
                System.out.println("Successfully changed language to English (United States).");
                break;
            case 1:
                pnFrom.setBorder(javax.swing.BorderFactory.createTitledBorder("Dari Celcius"));
                pnTo.setBorder(javax.swing.BorderFactory.createTitledBorder("Ke"));
                pnResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Keluaran"));
                btnConv.setText("Konversi");
                btnClose.setText("Tutup");
                System.out.println("Berhasil mengubah bahasa ke Bahasa Indonesia.");
                break;
            case 2:
                pnFrom.setBorder(javax.swing.BorderFactory.createTitledBorder("Tina Celcius"));
                pnTo.setBorder(javax.swing.BorderFactory.createTitledBorder("Kana"));
                pnResult.setBorder(javax.swing.BorderFactory.createTitledBorder("Kaluaran"));
                btnConv.setText("Robah");
                btnClose.setText("Tutup");
                System.out.println("Suksès ngarobah basa ka Basa Sunda.");
                break;
        }
        //lblResult.setText("");
        if (!txtCelcius.getText().equals("")) {
            konversi();
        }
    }//GEN-LAST:event_cmbLangItemStateChanged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void konversi() {
        double celcius = Double.parseDouble(txtCelcius.getText());
        double result = 0.0;
        String to = null, degree = null;
        
        if (cmbLang.getSelectedIndex() != 2) {
            switch (bgrTo.getSelection().getActionCommand()) {
                case "f":
                    to = "Fahrenheit";
                    break;
                case "k":
                    to = "Kelvin";
                    break;
                case "r":
                    to = "Reamur";
                    break;
            }
        } else {
            switch (bgrTo.getSelection().getActionCommand()) {
                case "f":
                    to = "Fahrenhèit";
                    break;
                case "k":
                    to = "Kèlvin";
                    break;
                case "r":
                    to = "Rèamur";
                    break;
            }
        }
        
        switch (bgrTo.getSelection().getActionCommand()) {
            case "f":
                degree = "°F";
                break;
            case "k":
                degree = "K";
                break;
            case "r":
                degree = "°R";
                break;
        }
        
        switch (bgrTo.getSelection().getActionCommand()) {
            case "f":
                result = celcius / 5 * 9 + 32;
                break;
            case "k":
                result = celcius + 273;
                break;
            case "r":
                result = celcius / 5 * 4;
                break;
        }
        
        switch(cmbLang.getSelectedIndex()) {
            case 0:
                lblResult.setText("Conversion result from " + txtCelcius.getText() + " °C to " + to + " is " + new DecimalFormat("##.##").format(result) + " " + degree);
                System.out.println(celcius + "°C to " + degree + " = " + result);
                break;
            case 1:
                lblResult.setText("Hasil konversi dari " + txtCelcius.getText() + " °C ke " + to + " adalah " + new DecimalFormat("##.##").format(result) + " " + degree);
                System.out.println(celcius + "°C ke " + degree + " = " + result);
                break;
            case 2:
                lblResult.setText("Hasil ngarobah tina " + txtCelcius.getText() + " °C kana " + to + " nyaèta " + new DecimalFormat("##.##").format(result) + " " + degree);
                System.out.println(celcius + "°C ka " + degree + " = " + result);
                break;
        }
    }
    
    private void btnConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvActionPerformed
        // TODO add your handling code here:
        konversi();
    }//GEN-LAST:event_btnConvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrTo;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnConv;
    private javax.swing.JComboBox<String> cmbLang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblResult;
    private javax.swing.JPanel pnFrom;
    private javax.swing.JPanel pnResult;
    private javax.swing.JPanel pnTo;
    private javax.swing.JTextField txtCelcius;
    // End of variables declaration//GEN-END:variables
}
